language: go
go:
  - 1.11.x

sudo: true

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.11/etcd-v3.3.11-linux-amd64.tar.gz -o etcd-v3.3.11-linux-amd64.tar.gz
  - tar xzvf etcd-v3.3.11-linux-amd64.tar.gz
  - ./etcd-v3.3.11-linux-amd64/etcd &

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v


script:
  - go test -v ./...
  - go test -v -tags=integration ./...

