language: go
go:
  - 1.11.4

sudo: true

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.11/etcd-v3.3.11-linux-amd64.tar.gz -o etcd-v3.3.11-linux-amd64.tar.gz
  - tar xzvf etcd-v3.3.11-linux-amd64.tar.gz
  - ./etcd-v3.3.11-linux-amd64/etcd &
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -v

script:
  - go test -v ./...

